name: automerge
on:
  workflow_dispatch:
  schedule:
    - cron: '42 2,5,8,11 * * *'

jobs:
  automerge:
    uses: salesforcecli/github-workflows/.github/workflows/automerge.yml@main
    with:
      GITHUB_TOKEN: ${{ secrets.IDEE_GH_TOKEN }}
    secrets: inherit
